### ISSUE TITLE
Rotate map

### ISSUE THREAD

**Issue by rudolfbyker** [tcassou/mapsplotlib#5]
This is a feature request.

Can we specify which direction is "up" on the map? I don't always want North to point upward.

**Comment by tcassou** [comment]
Hi @rudolfbyker,

On [Google Maps Static APIs doc](https://developers.google.com/maps/documentation/static-maps/intro) I did not find an easy way to do this (i.e. a url parameter). The closest thing I found was people manipulating the maps in Javascript, and rotating them by multiple of 90 degrees. In our case though we manipulate an image directly, not a complex data structure.

90 degrees rotations could could be done in python or matplotlib (e.g. for satellite maps without markers), however it would look bad in most cases (typically with the default - roadmap - map type) because of text and labels displayed on the maps.

Hope it helps!

Thomas

**Comment by tcassou** [comment]
@rudolfbyker should I close this issue? Unless you have suggestions?

**Comment by rudolfbyker** [comment]
I'm out of ideas, sorry. If it was my project, I would keep the issue open until somebody comes with a good suggestion, but you can close it if you like.

**Comment by tcassou** [comment]
Closing this since it's been open for more than a year, without good suggestions to fix it unfortunately. Thanks again for sharing!
